add systemd script
* systemd fixes

diff --git a/pkg/debian/postinst b/pkg/debian/postinst
--- a/pkg/debian/postinst
+++ b/pkg/debian/postinst
@@ -1,23 +1,41 @@
 #!/bin/sh
-update-rc.d $PKG_NAME defaults 91 09
+
+if [ -f /etc/init.d/$PKG_NAME ] ; then
+  update-rc.d $PKG_NAME defaults 91 09
+fi
 
 mkdir -p /var/lib/$PKG_NAME
 mkdir -p /etc/$PKG_NAME.conf.d
 
+legacy_start() {
+  /etc/init.d/$PKG_NAME stop || :
+
+  # Cleanup init's mess if it fails to stop
+  PIDFILE=/var/run/$PKG_NAME.pid
+  start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE --name rackspace-monit --signal KILL
+
+  # Start only if we find a config file in place
+  if [ -f /etc/$PKG_NAME.cfg ]; then
+    /etc/init.d/$PKG_NAME start || :
+  fi
+
+  exit $?
+}
+
 case "$1" in
     configure)
-         /etc/init.d/$PKG_NAME stop || :
-
-         # Cleanup init's mess if it fails to stop
-         PIDFILE=/var/run/$PKG_NAME.pid
-         start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE --name rackspace-monit --signal KILL
-
-         # Start only if we find a config file in place
-         if [ -f /etc/$PKG_NAME.cfg ]; then
-              /etc/init.d/$PKG_NAME start || :
-         fi
-        ;;
+      if [ -x "/etc/init.d/$PKG_NAME" ] || [ -e "/etc/init/$PKG_NAME.conf" ]; then
+        legacy_start
+      fi
+      if [ -x "/bin/systemctl"  ]; then
+        /bin/systemctl reload $PKG_NAME.service >/dev/null 2>&1 || true
+        /bin/systemctl enable $PKG_NAME.service >/dev/null 2>&1 || true
+        if [ -f "/etc/rackspace-monitoring-agent.cfg" ] ; then
+          /bin/systemctl restart $PKG_NAME.service >/dev/null 2>&1 || true
+        fi
+      fi
+      ;;
     *)
-        echo "Unrecognized postinst argument '$1'"
-        ;;
+      echo "Unrecognized postinst argument '$1'"
+      ;;
 esac
